# Generated by Django 6.0.6 on 2026-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizFy', '0002_topic_quizsession_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='total',
            field=models.IntegerField(default=15),
        ),
    ]
